# Generated by Django 5.1.4 on 2025-01-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('soin', 'Soin'), ('beauté', 'Beauté'), ('relaxation', 'Relaxation')], default='soin', max_length=50),
        ),
    ]
